name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Compilation avec le conteneur officiel Buildozer
        uses: kivy/buildozer-action@master
        with:
          command: android.debug

      - name: Récupération et sauvegarde de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: application-apk
          path: bin/*.apk
