name: CI Buildozer APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Compilation de l'APK Android avec Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android.debug

      - name: Télécharger l'artefact APK généré
        uses: actions/upload-artifact@v4
        with:
          name: package-apk
          path: bin/*.apk
